language: cpp

compiler:
  - clang
  - gcc

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.6

script: make

